let nome= "Marcos";
console.log(nome);
let numero= 12;
console.log(numero);
let ano= 2022;
console.log(ano-numero);
console.log(ano+numero);
let mensagem="Estou mexendo no console.log";
console.log(mensagem);
const quartaFeira=true;
console.log(quartaFeira);
console.log(typeof quartaFeira);